{{- if .Values.operations.enabled }}
apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: process-collector
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/resource-policy": keep
spec:
  processor:
    httpServer:
      path: /processor/processCollector
      scheme: http
    timeoutSeconds: 120
{{- end }}
