{{- if .Values.operations.enabled }}
apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: python-function
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/resource-policy": keep
spec:
  processor:
    function:
      codeSource:
        function.py: |
          from hello import hello


          def handler(context):
              hello()

              result = dict()
              for key in context:
                  result[key] = context[key]
              result["a"] = "1"
              result["b"] = "2"

              return result
        hello.py: |
          def hello():
              print("Hello World")
      runtime: Python3
    timeoutSeconds: 120
{{- end }}
