apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "kubediag-helm.fullname" . }}-admission-patch
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "kubediag-helm.fullname" . }}-admission-patch
    spec:
      containers:
      - name: patch
        image: {{ .Values.admissionWebhooks.patch.image.repository }}:{{ .Values.admissionWebhooks.patch.image.tag }}
        imagePullPolicy: {{ .Values.admissionWebhooks.patch.image.pullPolicy }}
        args:
        - patch
        - --webhook-name=kubediag-mutating-webhook-configuration
        - --namespace={{ .Release.Namespace }}
        - --secret-name=admission-webhook-secret
        - --patch-failure-policy=Fail
        - --patch-mutating=true
        - --patch-validating=false
        - \n
        - patch
        - --webhook-name=kubediag-validating-webhook-configuration
        - --namespace={{ .Release.Namespace }}
        - --secret-name=admission-webhook-secret
        - --patch-failure-policy=Fail
        - --patch-mutating=false
        - --patch-validating=true
        resources:
{{ toYaml .Values.admissionWebhooks.patch.resources | indent 10 }} 
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}  
      serviceAccountName: admission 
