apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admission-webhook-rolebinding
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admission-webhook-role
subjects:
  - kind: ServiceAccount
    name: admission
    namespace: {{ .Release.Namespace }}
