apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kubediag/serving-cert
  name: kubediag-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-diagnosis-kubediag-org-v1-diagnosis
  failurePolicy: Fail
  name: vdiagnosis.kb.io
  rules:
  - apiGroups:
    - diagnosis.kubediag.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - diagnoses
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-diagnosis-kubediag-org-v1-operation
  failurePolicy: Fail
  name: voperation.kb.io
  rules:
  - apiGroups:
    - diagnosis.kubediag.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - operations
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-diagnosis-kubediag-org-v1-operationset
  failurePolicy: Fail
  name: voperationset.kb.io
  rules:
  - apiGroups:
    - diagnosis.kubediag.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - operationsets
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-diagnosis-kubediag-org-v1-trigger
  failurePolicy: Fail
  name: vtrigger.kb.io
  rules:
  - apiGroups:
    - diagnosis.kubediag.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - triggers
