{{- if .Values.admissionWebhooks.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - webhook-service.{{ .Release.Namespace }}.svc
  - webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: admission-webhook-secret
{{- end -}}
